server:
  port: 9000
############################################################
#
# 配置数据源相关	使用阿里巴巴的 druid 数据源
#
############################################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.100:3306/test?useSSL=false
    username: root
    password: root
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true

############################################################
#
# mybatis 配置
#
############################################################
# mybatis 配置
mybatis:
  type-aliases-package: com.lx.springbootlearn.model
  mapper-locations: classpath:mapper/*.xml
# 通用 Mapper 配置
mapper:
  mappers: com.lx.springbootlearn.utils.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
