server:
  port: 9000
############################################################
#
# 配置数据源相关	使用阿里巴巴的 druid 数据源
#
############################################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recommend?useSSL=false
    username: cdss
    password: Cdss!2018
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
#  ############################################################
#  #
#  # redis 配置
#  #
#  ############################################################
#  redis:
#    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
#    database: 3
#    # redis服务器地址（默认为localhost）
#    host: 192.168.100.100
#    # redis端口（默认为6379）
#    port: 6379
#    # redis访问密码（默认为空）
#    password: Icd201809!78
#    # redis连接超时时间（单位为毫秒）
#    timeout: 0
#    # redis连接池配置
#    pool:
#      # 最大可用连接数（默认为8，负数表示无限）
#      max-active: 10
#      # 最大空闲连接数（默认为8，负数表示无限）
#      max-idle: 10
#      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
#      min-idle: 0
#      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#      max-wait: -1
############################################################
#
# mybatis 配置
#
############################################################
# mybatis 配置
mybatis:
  type-aliases-package: com.lx.springbootlearn.model
  mapper-locations: classpath:mapper/*.xml
## 通用 Mapper 配置
#mapper:
#  mappers: com.lx.springbootlearn.utils.MyMapper
#  not-empty: false
#  identity: MYSQL
# 分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: countSql


